[package]
name = "testhacks"
version = "0.1.0"
edition = "2024"

[dependencies]
hklib = { path = "../hklib" }
windows = { version = "0.62.0", features = ["Win32_Graphics_Gdi", "Win32_Graphics_OpenGL"] }

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "builder"
path = "src/builder/main.rs"
