[package]
name = "ACmultihack"
version = "0.1.0"
edition = "2024"

[dependencies]
hklib = { path = "../hklib" }

imgui = "0.12.0"
rand = "0.9.2"
windows = { version = "0.62.0", features = ["Win32_Graphics_Gdi", "Win32_Graphics_OpenGL"] }

[lib]
crate-type = ["cdylib"]
